#!/bin/bash
tx_hash="$1"
retrieve(){
if [[ $(wc -m <<<"$tx_hash") == 65 ]]; then
        echo "bcat tx:   $tx_hash"
else
        printf '%s' "error ; tx_hash not 64 chars"
        return
fi

hash2asm(){

bsv_net='main'
bsv_api='v1'
tx_vout=0

if [[ $(wc -m <<<"$tx_hash") == 65 ]]; then
        get_hex="$(curl -s --location --request GET  \
                https://api.whatsonchain.com/"$bsv_api"/bsv/"$bsv_net"/tx/"$tx_hash"/out/"$tx_vout"/hex)"
else
        printf '%s' "error; tx_hash not 64 chars"
        return
fi

asm_txo=$(node<<<"let bsv = require('bsv'); var script = bsv.Script.fromHex('$get_hex');console.log(script.toAsmString())")

if [[ -z "$asm_txo" ]]; then
        printf '%s' "error; asm returned null"
        return
fi

if [[ "$(cut -d ' ' -f 3 <<<"$asm_txo")" ==  313544484678575a4a54353866396e6879476e735242717267774b34573668345570 ]]; then
        asm_arr="$(tr ' ' '\n' <<<"$asm_txo")"
        bcatPts="$(sed '1,8d' <<<"$asm_arr")"
        bc_Name="$(cut -d ' ' -f 7 <<<"$asm_txo" | xxd -r -p)"
        printf '%s\n' "$(wc -l <<<"$bcatPts") bcat parts:"
        #       bc_Info="$(cut -d ' ' -f 5 <<<"$asm_txo")"
        #       bc_Mime="$(cut -d ' ' -f 6 <<<"$asm_txo")"
        #       bc_Flag="$(cut -d ' ' -f 8 <<<"$asm_txo")"
elif [[ "$(cut -d ' ' -f 3 <<<"$asm_txo")" ==  31436844487a646431483477536a67474d48796e645a6d3671784544476a71704a4c ]]; then
        xxd -r -p <<<"$(cut -d ' ' -f 4 <<<"$asm_txo")" >> "$bc_Name"
else
        printf '%s' "error; not a bcat transaction hash"
fi
}

hash2asm

while read -r line; do
        tx_hash="$line"
        printf '%s\n' "bcat part: $line"
        hash2asm
done<<<"$bcatPts"

echo "$bc_Name"
}
retrieve
